MODULE MATRIX_IO

USE ALG_MATH

CONTAINS


SUBROUTINE READ_DENSE(PROBLEM_NAME, FORMAT_STYLE, A_MTX)
	

	CHARACTER(LEN=20) PROBLEM_NAME
	INTEGER FORMAT_STYLE	
	TYPE(DENSE_MATRIX) :: A_MTX
	REAL, ALLOCATABLE ::  A_ARR(:)


	CHARACTER(LEN=30) DATA_FILE
	LOGICAL :: MATRIXFILE_EXISTS
	INTEGER :: DATA_FILE_UNIT, A_HEIGHT, A_WIDTH

	INTEGER :: I
	REAL :: A_VAL


	A_VAL = 0

	MTX_HEIGHT = 0; MTX_WIDTH = 0

	IF (FORMAT_STYLE .EQ. 0) THEN
		DATA_FILE = "data/" // TRIM(PROBLEM_NAME) // ".txt"
				
		INQUIRE(FILE=DATA_FILE, exist=MATRIXFILE_EXISTS)
		IF(.NOT. MATRIXFILE_EXISTS) THEN 
			GOTO 200
		ELSE 
			GOTO 201

		END IF
	END IF
200 WRITE(*, '(A)') 'No matrix file named: ' //  DATA_FILE 
	RETURN

201 OPEN(NEWUNIT=DATA_FILE_UNIT, FILE=DATA_FILE, &
	ACTION='READ', ERR=202)
	
	READ(DATA_FILE_UNIT, *) A_HEIGHT, A_WIDTH

	IF (ALLOCATED(A_ARR)) DEALLOCATE(A_ARR)

	ALLOCATE( A_ARR( A_HEIGHT * A_WIDTH))
	
	DO I=1,A_HEIGHT
		READ(DATA_FILE_UNIT, *) A_ARR((I-1) * A_WIDTH + 1:(I-1) * A_WIDTH + A_WIDTH)

	END DO
	CLOSE(DATA_FILE_UNIT)	

	A_MTX%A_ARR = A_ARR
	A_MTX%A_HEIGHT=A_HEIGHT; A_MTX%A_WIDTH=A_WIDTH

	GOTO 300	

202 WRITE(*, '(A)') "Error while reading matrix file"


300 RETURN
END SUBROUTINE

SUBROUTINE READ_UFCSR(PROBLEM_NAME, FORMAT_STYLE, A_VAL, A_COL, A_CSR)


END SUBROUTINE
	

END MODULE
