MODULE DENSE_IO

CONTAINS

SUBROUTINE READ_DENSE(PROBLEM_NAME, FORMAT_STYLE, A_ARR)
	
	CHARACTER(LEN=20) PROBLEM_NAME
	INTEGER FORMAT_STYLE	
	REAL, ALLOCATABLE ::  A_ARR(:)


	CHARACTER(LEN=30) DATA_FILE
	LOGICAL :: MATRIXFILE_EXISTS
	INTEGER :: DATA_FILE_UNIT, A_HEIGHT, A_WIDTH

	INTEGER :: I
	REAL :: A_VAL

	A_VAL = 0

	A_HEIGHT = 0; A_WIDTH = 0

	WRITE(*, *) LEN(PROBLEM_NAME)
	IF (FORMAT_STYLE .EQ. 0) THEN
		DATA_FILE = "data/" // TRIM(PROBLEM_NAME) // ".txt"
				
		INQUIRE(FILE=DATA_FILE, exist=MATRIXFILE_EXISTS)
		IF(.NOT. MATRIXFILE_EXISTS) THEN 
			GOTO 200
		ELSE 
			GOTO 201

		END IF
	END IF
200 WRITE(*, '(A)') 'No matrix file named: ' //  DATA_FILE 
	RETURN

201 OPEN(NEWUNIT=DATA_FILE_UNIT, FILE=DATA_FILE, &
	ACTION='READ', ERR=202)
	
	READ(DATA_FILE_UNIT, *) A_HEIGHT, A_WIDTH

	WRITE(*, '(A,I5,I5)') "Problem size: ", A_HEIGHT, A_WIDTH

	WRITE(*, *) A_HEIGHT, A_WIDTH
	ALLOCATE( A_ARR( A_HEIGHT * A_WIDTH))
	
	DO I=1,A_HEIGHT
		READ(DATA_FILE_UNIT, *) A_ARR((I-1) * A_WIDTH + 1:(I-1) * A_WIDTH + A_WIDTH)
		WRITE(*, *) A_ARR((I-1) * A_WIDTH + 1:(I-1) * A_WIDTH + A_WIDTH)

	END DO

	GOTO 300	

202 WRITE(*, '(A)') "Error while reading matrix file"


300 RETURN
END SUBROUTINE



END MODULE
