SUBROUTINE READ_DENSE(PROBLEM_NAME, FORMAT_STYLE)
	
	CHARACTER(LEN=20) PROBLEM_NAME
	INTEGER FORMAT_STYLE
	
	CHARACTER(LEN=30) DATA_FILE

	WRITE(*, *) LEN(PROBLEM_NAME)
	IF (FORMAT_STYLE .EQ. 0) THEN
		DATA_FILE = "data/" // TRIM(PROBLEM_NAME) // ".txt"

		WRITE(*, *) DATA_FILE
	END IF



END
