SUBROUTINE UPDATE_CONFIG(COMMANDS, OPTIONS, MATRIXFILE, N_COMMANDS)

	INTEGER :: N_COMMANDS
	
	INTEGER :: COMMANDS(N_COMMANDS)
	INTEGER :: OPTIONS(N_COMMANDS)

	CHARACTER :: MATRIXFILE(20)

	
	WRITE(*, '(A)') "updated options form config file"


END
