SUBROUTINE UPDATE_CONFIG(OPTIONS, PROBLEM_NAME, N_OPTIONS)

	INTEGER :: N_OPTIONS
	INTEGER :: OPTIONS(N_OPTIONS)
	CHARACTER(20) :: PROBLEM_NAME

	CHARACTER(12) :: CONFIGFILE_NAME
	LOGICAL :: CONFIGFILE_EXISTS
	INTEGER :: CONFIGFILE_UNIT, CONFIGFILE_ERR

	CHARACTER(20) :: CURR_OPTIONNAME
	INTEGER :: CURR_OPTIONVALUE

	CONFIGFILE_NAME = 'solve.config'

	INQUIRE(FILE=CONFIGFILE_NAME, exist=CONFIGFILE_EXISTS)

	IF(.NOT. CONFIGFILE_EXISTS) GOTO 200

	OPEN(NEWUNIT=CONFIGFILE_UNIT, FILE=CONFIGFILE_NAME, &
	ACTION='READ', ERR=201)

	DO
		READ(CONFIGFILE_UNIT, *, END=202) CURR_OPTIONNAME &
		, CURR_OPTIONVALUE
		WRITE(*, '(A,I2)') CURR_OPTIONNAME, CURR_OPTIONVALUE
	END DO

202 WRITE(*, *) "Finished reading input file"


	GOTO 201
	
200	WRITE(*, '(A)') 'No config files exists &
	 &using default options'
201 RETURN

END
